name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
version: 0.1.6
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  collection: ^1.14.6
  url_launcher: ^5.0.0
  quill_delta: ^1.0.0
  notus: ^0.1.0
  meta: ^1.1.0
  quiver_hashcode: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
