name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 0.12.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.13
  url_launcher: ^5.7.10
  quill_delta: ^2.0.0
  #notus: ^0.1.5
  notus:
    #path: ../notus/
    git:
      url: git://github.com/zeusbaba/zefyr.git
      path: packages/notus/
  meta: ^1.2.4
  quiver_hashcode: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
